apiVersion: v1
kind: ConfigMap
metadata:
  name: database
  labels:
    app: database
data:
  db.host: "localhost"
  db.port: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: database
  labels:
    app: database
type: Opague
stringData:
  db.user: "admin"
  db.password: "admin123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: quay.io/redhattraing/postgres-database:v1.0
        ports:
        - containerPort: 5432
          envForm:
          - configMapRef:
              name: database
          - secretRef:
              name: database
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
