apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: quay.io/redhattraining/mariadb:10.5
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: database
        - secretRef:
            name: database
        # --- ADD THIS SECTION ---
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      # --- ADD THIS SECTION ---
      volumes:
      - name: mysql-data
        emptyDir: {}
