apiVersion: v1
kind: Service
metadata:
  name: secure-app-svc
  namespace: network-security-tls
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: secure-app-certs
spec:
  selector:
    app: secure-app
  ports:
    - port: 8443
      targetPort: 8443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secure-nginx-conf
  namespace: network-security-tls
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 8443 ssl;
        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;
        location / {
          return 200 'This is the SECURE application (HTTPS inside the pod)!\n';
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-app
  namespace: network-security-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      containers:
        - name: nginx
          image: quay.io/redhattraining/hello-world-nginx
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: certs
              mountPath: /etc/nginx/certs
              readOnly: true
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: certs
          secret:
            secretName: secure-app-certs
        - name: config
          configMap:
            name: secure-nginx-conf
