# Grant admin access to developer in test1
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-admin-binding
  namespace: network-ingress-test1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io
---
# Grant admin access to developer in test2
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-admin-binding
  namespace: network-ingress-test2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io
---
# Grant admin access to developer in test2
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-admin-binding
  namespace: network-ingress-test3
rolRef:
  apiGroup: rbac.authorization.k8s.io
    apiGroup: ClusterRole
    name: admin
subjects:
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io
